name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message) , ', ') }}

  # the below will be 'true'
  SKIP_CONDITION: ${{ contains(${{COMMIT_MESSAGES}}, '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e test
        run: npm run test:e2e
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
  tag_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        if: ${{env.SKIP_CONDITION == 'true'}}
          run: echo 'this step is skipped'
        if: ${{env.SKIP_CONDITION == 'false'}}
          run: echo 'this step is NOT skipped'
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
